### ISSUE TITLE
YANG validation does not produce any report

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#11] opened 2018-05-16 23:43 UTC
[Fetch, extract , and validate ](http://www.yangvalidator.com/) doesn't produce any output when Upload Internet Draft option used.
Appreciate your suggestions and help.

Regards,
Greg

**Comment by miroslavKovacPantheon** [comment] 2019-08-22 17:20
The same question as in #12

**Comment by miroslavKovacPantheon** [comment] 2020-01-24 13:31
Closing as duplicate of #12 and invalid for no answer

**Closed by miroslavKovacPantheon** 2020-01-24 13:31 UTC
Labels: Priority: Critical, question
